# WARNING
# YAML is space sensitive. Tabs are not allowed!
development:
  adapter: postgresql
  encoding: unicode
  database: learningrails_development
  pool: 5
  username: learningrails
  password: LearningRailsPass

test:
  adapter: postgresql
  encoding: unicode
  database: learningrails_test
  pool: 5
  username: learningrails
  password: LearningRailsPass

production:
  adapter: postgresql
  encoding: unicode
  database: learningrails_production
  pool: 5
  username: learningrails
  password: LearningRailsPass
